Add negative matchers for inhibitors
prometheus/alertmanager pull request #2460
Opened 2021-01-19 06:11 UTC by aSquare14

Related issue : #1023
Related Pull Requests : #2456 #2434 #2441 
Signed-off-by: aSquare14 <atibhi.a@gmail.com>

2021-01-20 16:14 UTC, aSquare14 commented
cc @beorn7 @vladimiroff @simonpasquier  Could you please review this.

2021-01-21 23:34 UTC, beorn7 requested changes
I think this works. Just a few nits about the doc comments.

2021-01-22 02:59 UTC, aSquare14 commented on config/config.go
> +	// value for source alerts. It also does regular expression matching.
Done

2021-01-22 14:51 UTC, beorn7 approved these changes
Great, thank you.

2021-01-22 14:53 UTC, beorn7 commented
I got in touch with @simonpasquier , BTW. He is really spread thin at the moment. It will get better, but we also try to find a co-maintainer for him. In the meantime, I'll merge PRs where I'm reasonably confident. Like this one. (o:

2021-01-22 14:54 UTC, merged

2021-01-22 14:57 UTC, aSquare14 commented
Thanks for merging and the reviews :)