Add support to set the Slack URL in a file
prometheus/alertmanager pull request #2534
Opened 2021-04-02 01:59 UTC by julienduchesne

- Added support for the file in both the global and the lower level
- Tried to follow configuration patterns I saw in prometheus
- The slack file is read on every request as mentioned in the prometheus issue to enable seamless switches

https://github.com/prometheus/alertmanager/issues/2498

2021-04-12 20:51 UTC, beorn7 approved these changes
I think this works. @roidelapluie @simonpasquier do you want to have a look, too?

2021-04-12 20:51 UTC, beorn7 commented on config/testdata/conf.slack-no-api-url.yml
> +    text: 'test'
No newline at end of file.

2021-04-12 20:51 UTC, beorn7 commented on config/testdata/conf.slack-default-api-url-file.yml
> +
No newline at end of file. (But some whitespace on line 22, which just needs to be deleted?)

2021-04-12 20:51 UTC, beorn7 commented on config/testdata/conf.slack-both-file-and-url.yml
> +
No newline at end of file. (But some whitespace on line 22, which just needs to be deleted?)

2021-04-12 20:53 UTC, beorn7 commented
Of course, eventually we have to do the same for the other fields listed in #2498 . Not sure if we can reuse some code or just have to do it all individually.

2021-04-12 20:56 UTC, beorn7 requested changes
Just realized that docs/configuration.md needs to be updated, too. And perhaps an example in docs/notification_examples.md .

2021-04-13 14:56 UTC, beorn7 approved these changes
Thank you.

2021-04-13 14:56 UTC, beorn7 commented
@julienduchesne unfortunately, now the DCO is missing on a commit. See https://github.com/prometheus/alertmanager/pull/2534/checks?check_run_id=2332859284

2021-04-13 14:59 UTC, julienduchesne commented
> @julienduchesne unfortunately, now the DCO is missing on a commit. See https://github.com/prometheus/alertmanager/pull/2534/checks?check_run_id=2332859284

Sorry about that. Fixed 👍

2021-04-13 15:12 UTC, beorn7 commented
Cool. Merging now, assuming that silence from @simonpasquier and @roidelapluie means consent. :->

2021-04-13 15:12 UTC, merged