Adding the alert info pagination API
prometheus/alertmanager pull request #3425
Opened 2023-07-18 17:30 UTC by qinxx108

Implement the proposal here https://github.com/prometheus/alertmanager/issues/3361

2023-08-02 07:17 UTC, emanlodovice requested changes

2023-08-02 07:17 UTC, emanlodovice commented on api/v2/api_test.go
> +			r, err := http.NewRequest("GET", "/api/v2/alerts", nil)
Should this be `/api/v2/alertinfos`?

2023-08-09 05:26 UTC, qinxx108 commented on api/v2/restapi/operations/alertmanager_api.go
> +	o.handlers["POST"]["/alertinfos"] = alert.NewPostAlerts(o.context, o.AlertPostAlertsHandler)
the openapi.yml get messed up. Fixed it

2023-08-09 05:26 UTC, qinxx108 commented on api/v2/restapi/operations/alert/post_alerts_urlbuilder.go
> +	var _path = "/alertinfos"
the openapi.yml get messed up. Fixed it

2023-08-09 05:26 UTC, qinxx108 commented on api/v2/restapi/operations/alert/post_alerts.go
> +	PostAlerts swagger:route POST /alertinfos alert postAlerts
the openapi.yml get messed up. Fixed it

2023-08-09 05:27 UTC, qinxx108 commented on api/v2/client/alert/alert_client.go
> +		PathPattern:        "/alertinfos",
the openapi.yml get messed up. Fixed it

2023-08-09 05:27 UTC, qinxx108 commented on api/v2/client/alert/post_alerts_responses.go
> +	return fmt.Sprintf("[POST /alertinfos][%d] postAlertsOK ", 200)
the openapi.yml get messed up. Fixed it

2023-08-09 05:38 UTC, qinxx108 commented on api/v2/api.go
> +		if nextToken != nil && *nextToken >= a.Fingerprint().String() {
done

2023-08-09 05:39 UTC, qinxx108 commented on api/v2/api.go
>  		return alert_ops.NewGetAlertsInternalServerError().WithPayload(err.Error())
good catch, fixed

2023-08-10 06:51 UTC, emanlodovice approved these changes

2023-09-13 09:45 UTC, closed without merging