Add summary to msteams notification
prometheus/alertmanager pull request #3616
Opened 2023-11-23 10:38 UTC by romankubu

Hi,
currently msteams notification does not support summary atribute from Message card. Result is that in Activity (inside MS Teams) you don't know what kind of alert you received and you need to klik on it. It is same for notification on phone etc.

Example (bottom one is without pull request, top one is with pull request):
<img width="306" alt="image" src="https://github.com/prometheus/alertmanager/assets/112698283/a31f9989-4c43-49ef-a93c-f7c6080a3d2c">

2023-11-23 10:48 UTC, romankubu commented
If i run `go run -tags=dev asset_generate.go` in `/assets` then those alerts are working well. How can i fix it?

2023-11-24 02:25 UTC, zhan9san requested changes

2023-11-24 02:25 UTC, zhan9san commented on docs/configuration.md
> +# Message title template.
I guess it's a typo

```suggestion
# Message summary template.
```

2023-11-24 07:16 UTC, romankubu commented on docs/configuration.md
> +# Message title template.
Thanks i missed that

2023-11-24 08:47 UTC, gotjosh approved these changes
LGTM

Thank you very much for your contribution.

2023-11-24 08:58 UTC, merged

2023-12-10 15:01 UTC, rgarcia89 commented
Someone knows if a new release will be created close by? This is a very unfavorable bug